# 🗄️ Banco de Dados e Computação em Nuvem (BDCN)
## Notebook Integrado de Recuperação e Aprofundamento — Modelo Conceitual, Cardinalidade, Junções Externas e Junções Múltiplas

---

### 🏫 Informações institucionais

| Campo | Informação |
|---|---|
| **Escolas atendidas** | E.E. Dona Benedita Freire de Macedo (**EEBFM**) e E.E. Prof. João Cruz (**EEJC**) |
| **Rede** | Secretaria da Educação do Estado de São Paulo (SEDUC-SP) — Unidade Regional de Ensino de Jacareí (URE-Jacareí) |
| **Professor** | Heglas Oliveira |
| **E-mail institucional** | heglasoliveira@professor.educacao.sp.gov.br |
| **E-mail institucional (alternativo)** | heglasoliveira@prof.educacao.sp.gov.br |
| **Componente curricular** | Banco de Dados e Computação em Nuvem (BDCN) |
| **Ação pedagógica** | RECUPERAÇÃO E APROFUNDAMENTO |
| **Semana** | 27 a 31 de julho de 2026 |

### 🏫 Turmas, datas e horários

| Escola | Turma | Data | Horário | Conteúdo da aula |
|---|---|---|---|---|
| **EEBFM** | 3ª Série A — Técnico | Quarta-feira, 29/07/2026 | 19h35 (Aula 1) | Modelos conceituais: entidades, atributos, relacionamentos, cardinalidade e participação |
| **EEBFM** | 3ª Série A — Técnico | Quarta-feira, 29/07/2026 | 20h25 (Aula 2) | Junções externas e junções múltiplas (formato **integrado**) |
| **EEJC** | 3ª BT | Quinta-feira, 30/07/2026 | 08h40–09h30 | Modelos conceituais, cardinalidade e participação |
| **EEJC** | 3ª BT | Sexta-feira, 31/07/2026 | 07h00–07h50 | Junções externas |
| **EEJC** | 3ª BT | Sexta-feira, 31/07/2026 | 07h50–08h40 | Junções múltiplas |

---

### 🧭 Como usar este notebook em cada escola

Este é um **único notebook**, construído para atender **duas rotas de uso diferentes**, de acordo com a quantidade de aulas disponíveis em cada escola nesta semana. As seções estão numeradas e sinalizadas para que fique claro **onde parar/retomar** em cada encontro.

| Escola | Rota | Nº de aulas | Como percorrer o notebook |
|---|---|---|---|
| **EEBFM** (3ª Série A Técnico) | **Rota condensada** | 2 aulas em um único dia (29/07, 19h35 e 20h25) | **Aula 1 (19h35):** Diagnóstico inicial → Módulo 1 completo (modelo conceitual, entidades, cardinalidade e participação). **Aula 2 (20h25):** Módulo 2 (LEFT JOIN) **+** Módulo 3 (junções múltiplas) de forma **integrada**, seguidos do desafio final, ticket de saída e rubrica. |
| **EEJC** (3ª BT) | **Rota expandida** | 3 aulas em dois dias (30/07 e 31/07) | **Aula 1 (30/07, 08h40–09h30):** Diagnóstico inicial → Módulo 1 completo. **Aula 2 (31/07, 07h00–07h50):** Módulo 2 (LEFT JOIN), com tempo maior para prática. **Aula 3 (31/07, 07h50–08h40):** Módulo 3 (junções múltiplas) + desafio final, ticket de saída e rubrica. |

> 💡 Os marcadores **🟦 AULA 1**, **🟩 AULA 2** e **🟨 AULA 3** ao longo do notebook indicam o ponto de início sugerido de cada encontro. A EEBFM usa apenas os marcadores 🟦 e 🟩 (juntando Módulo 2 e Módulo 3 na mesma aula); a EEJC usa os três marcadores, um por aula.

---

### ℹ️ Como usar este notebook (instruções gerais)

Este material foi construído para ser executado no **Google Colab** ou em **Jupyter Notebook**, utilizando apenas a biblioteca padrão do Python (`sqlite3`) e bibliotecas gratuitas amplamente disponíveis (`pandas`).

- Você não precisa instalar nada além do ambiente padrão do Colab.
- **Não é necessário acesso à internet, downloads ou arquivos externos**: todo o banco de dados usado é **fictício** e é criado diretamente dentro do notebook, em memória, usando `sqlite3`.
- Sempre que houver uma célula marcada com **✏️ Espaço para resposta/código**, é ali que você deve escrever sua consulta SQL ou resposta.
- As células marcadas com **✅ Verificação automática** usam a função `verificar(...)` e/ou `assert` para conferir sua resposta. Se nada aparecer de erro, está certo! Se aparecer um aviso ou `AssertionError`, revise sua consulta.
- As soluções do professor ficam **escondidas** em blocos recolhíveis `<details>` (clique para abrir). Tente resolver sozinho(a) antes de conferir.
- Para quem preferir, há sempre uma **alternativa sem código** (cartões/tabelas para preencher à mão) e consultas **parcialmente preenchidas**.

> 💡 **Dica:** no Google Colab, para executar uma célula, clique nela e pressione `Shift + Enter`. Execute as células **em ordem**, de cima para baixo.

---

### 🗺️ Agenda visual numerada

1. **Abertura e diagnóstico inicial** — o que já sabemos sobre modelos de banco de dados e consultas SQL?
2. 🟦 **Módulo 1 — Modelo conceitual:** entidades, atributos, chave primária, relacionamentos, cardinalidade (1:1, 1:N, N:N) e participação (opcional/obrigatória).
3. **Construção da base escolar simulada** em SQLite (tabelas `turmas`, `estudantes`, `componentes`, `matriculas`).
4. 🟩 **Módulo 2 — Junções externas:** `INNER JOIN` x `LEFT JOIN`, registros sem correspondência, comparação visual.
5. 🟨 **Módulo 3 — Junções múltiplas:** consultas com três ou mais tabelas, aliases, seleção de colunas e ordenação.
6. **Desafio final integrador** — modelagem + consulta de três tabelas.
7. **Atividade de aprofundamento**, **ticket de saída** e **rubrica formativa**.

---

### ♿ Acessibilidade deste material

- Instruções curtas, em blocos numerados e passo a passo.
- Glossário simples ao final de cada módulo, com palavras-chave explicadas em linguagem direta.
- **Alternativa sem código**: cartões/tabelas para preencher à mão, representando o modelo ER ou o resultado da consulta, sem exigir digitação de SQL.
- Consultas **parcialmente preenchidas** (com lacunas `___`) para quem precisar de apoio adicional.
- Códigos organizados em blocos pequenos, com comentários explicando cada linha.
- Atividade de aprofundamento separada, para quem quiser ir além do previsto na aula.

**Este notebook não contém nomes, diagnósticos ou qualquer dado pessoal de estudantes da Educação Especial ou de qualquer outro estudante.** Todos os identificadores usados na base de dados fictícia são códigos genéricos (ex.: `EST001`), sem qualquer vínculo com pessoas reais.

In [1]:
# Configuração inicial do ambiente
# Usamos apenas bibliotecas padrão do Python (sqlite3) e bibliotecas gratuitas comuns (pandas)

import sqlite3
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

print("Ambiente configurado com sucesso!")
print("Bibliotecas carregadas: sqlite3 (padrão do Python) e pandas.")

Ambiente configurado com sucesso!
Bibliotecas carregadas: sqlite3 (padrão do Python) e pandas.

In [2]:
# Função auxiliar de verificação automática
# Ela avisa quando o exercício ainda não foi resolvido (valor None) e só valida quando houver uma resposta.

def verificar(condicao, mensagem_erro, ainda_nao_resolvido=False):
    # Confere uma condição booleana e imprime um retorno amigável.
    # Se 'ainda_nao_resolvido' for True, apenas lembra o estudante de completar o exercício.
    if ainda_nao_resolvido:
        print("📝 Ainda não resolvido — complete o código acima antes de verificar.")
        return
    if condicao:
        print("✅ Resposta correta! Muito bem.")
    else:
        print("❌ Ainda não está certo. Dica:", mensagem_erro)


def mostrar_consulta(cursor_ou_df, titulo=None):
    # Função auxiliar para exibir o resultado de uma consulta SQL de forma organizada.
    if titulo:
        print(f"--- {titulo} ---")
    return cursor_ou_df

## 🔎 Diagnóstico inicial (5 minutos)

Antes de começar, responda rapidamente — sem se preocupar em errar! Isso nos ajuda a saber de onde partir.

**Perguntas de sondagem** (responda mentalmente, em voz alta na aula, ou por escrito abaixo):

1. Quando você pensa em um "banco de dados de uma escola", quais **"coisas" (entidades)** vêm à sua mente? (ex.: aluno, turma...)
2. O que você entende por **cardinalidade** em um relacionamento entre duas tabelas?
3. Você já ouviu falar em `JOIN` em SQL? O que você imagina que ele faça?
4. Você sabe explicar a diferença entre um `INNER JOIN` e um `LEFT JOIN`?

> Não existe resposta errada aqui — o objetivo é ativar o que você já sabe antes de avançarmos.

In [3]:
# Diagnóstico inicial rápido — registre suas respostas como texto (fictício, apenas para você mesmo)
# ✏️ Espaço para resposta/código

resposta_1_entidades = "Escreva aqui as entidades que você imagina em um banco de dados escolar..."
resposta_2_cardinalidade = "Escreva aqui o que você entende por cardinalidade..."
resposta_3_join = "Escreva aqui o que você imagina que um JOIN faça..."
resposta_4_inner_left = "Escreva aqui a diferença entre INNER JOIN e LEFT JOIN, se souber..."

print("Diagnóstico inicial registrado. Vamos conferir e aprofundar essas ideias ao longo do notebook!")

Diagnóstico inicial registrado. Vamos conferir e aprofundar essas ideias ao longo do notebook!

---
# 🟦 AULA 1 — Módulo 1: Modelo Conceitual, Entidades, Atributos e Relacionamentos

**Defasagem trabalhada:** identificar entidades, atributos e relacionamentos; interpretar cardinalidade e participação.

## Passo 1 — O que é um modelo conceitual?

Antes de criar qualquer tabela em um banco de dados, é preciso **planejar** o que será armazenado. Esse planejamento é chamado de **modelo conceitual** (ou **modelo Entidade-Relacionamento**, também chamado de **DER** — Diagrama Entidade-Relacionamento).

O modelo conceitual descreve, de forma visual e independente de tecnologia:

- **Entidades**: as "coisas" ou "objetos" do mundo real que queremos representar (ex.: `Estudante`, `Turma`, `Componente Curricular`).
- **Atributos**: as características de cada entidade (ex.: um `Estudante` tem `código do estudante`, `data de nascimento fictícia`).
- **Chave primária**: o atributo (ou conjunto de atributos) que identifica **de forma única** cada ocorrência de uma entidade (ex.: `codigo_estudante`).
- **Relacionamentos**: as conexões entre entidades (ex.: um `Estudante` **está matriculado em** uma `Turma`).
- **Cardinalidade**: quantas ocorrências de uma entidade se relacionam com quantas ocorrências de outra.
- **Participação**: se toda ocorrência de uma entidade **precisa** (obrigatória) ou **não precisa** (opcional) participar do relacionamento.

> 💬 **Analogia:** o modelo conceitual é como a **planta de uma casa** antes de construí-la. Antes de "erguer as paredes" (criar as tabelas no banco de dados), desenhamos como os cômodos (entidades) se conectam.

## Passo 2 — Entidades, atributos e chave primária

Vamos usar como exemplo um recorte da nossa base escolar fictícia. Observe a entidade abaixo:

### 🧩 Entidade: `Estudante`

| Atributo | Exemplo fictício | Observação |
|---|---|---|
| **codigo_estudante** (PK) | `EST001` | Chave primária — identifica cada estudante de forma única |
| nome_ficticio | `Estudante Alfa` | Nome genérico, sem dado real |
| turma_codigo | `T01` | Liga o estudante a uma turma (chave estrangeira) |

- A **chave primária** (PK, do inglês *primary key*) é marcada para deixar claro que **não pode se repetir** e **não pode ficar vazia** — é o "RG" daquela entidade dentro do banco de dados.
- Um atributo que aponta para a chave primária de **outra** entidade é chamado de **chave estrangeira** (FK, *foreign key*) — é o que permitirá, mais adiante, fazer os `JOIN`s entre tabelas.

### 🧩 Outras entidades do nosso cenário

| Entidade | Exemplos de atributos | Chave primária |
|---|---|---|
| **Turma** | codigo_turma, nome_turma, turno | codigo_turma |
| **Componente** | codigo_componente, nome_componente, carga_horaria | codigo_componente |
| **Matrícula/Resultado** | codigo_matricula, codigo_estudante (FK), codigo_componente (FK), resultado | codigo_matricula |

### 📖 Glossário simples — Entidades e atributos

| Termo | Explicação simples |
|---|---|
| **Entidade** | Uma "coisa" do mundo real que queremos guardar informações (ex.: Estudante, Turma). |
| **Atributo** | Uma característica da entidade (ex.: nome, código). |
| **Chave primária (PK)** | O atributo que identifica cada registro de forma única, sem repetição. |
| **Chave estrangeira (FK)** | Um atributo que "aponta" para a chave primária de outra entidade, criando o relacionamento. |
| **Relacionamento** | A ligação/associação entre duas (ou mais) entidades. |

### ✏️ Exercício 1 — Identificando entidades, atributos e chave primária

Observe a lista de campos fictícios abaixo, coletados sem organização de um caderno de anotações:

`codigo_componente`, `nome_ficticio`, `nome_componente`, `codigo_estudante`, `carga_horaria`, `turma_codigo`

Complete o código abaixo, classificando cada campo.

**Alternativa sem código:** desenhe (no papel ou em um cartão) duas caixas — uma para `Estudante` e outra para `Componente` — e distribua os campos acima em cada caixa, sublinhando a chave primária de cada uma.

In [4]:
# ✏️ Espaço para resposta/código — Exercício 1
# Preencha as listas abaixo com os campos que pertencem a cada entidade (como strings)

campos_estudante = None       # substitua por uma lista, ex.: ["codigo_estudante", "nome_ficticio", "turma_codigo"]
campos_componente = None      # substitua por uma lista, ex.: ["codigo_componente", "nome_componente", "carga_horaria"]
chave_primaria_estudante = None    # substitua pela string "codigo_estudante"

print("Campos de Estudante:", campos_estudante)
print("Campos de Componente:", campos_componente)
print("Chave primária de Estudante:", chave_primaria_estudante)

Campos de Estudante: None
Campos de Componente: None
Chave primária de Estudante: None

<details>
<summary>🔓 <b>Clique aqui para ver a solução do professor — Exercício 1</b></summary>

```python
campos_estudante = ["codigo_estudante", "nome_ficticio", "turma_codigo"]
campos_componente = ["codigo_componente", "nome_componente", "carga_horaria"]
chave_primaria_estudante = "codigo_estudante"
```

**Explicação:** `codigo_estudante`, `nome_ficticio` e `turma_codigo` descrevem um **Estudante**. `codigo_componente`, `nome_componente` e `carga_horaria` descrevem um **Componente**. A chave primária de `Estudante` é `codigo_estudante`, pois identifica cada estudante de forma única.
</details>

In [5]:
# ✅ Verificação automática — Exercício 1
_pendente = campos_estudante is None or campos_componente is None or chave_primaria_estudante is None
if not _pendente:
    _ok_estudante = set(campos_estudante) == {"codigo_estudante", "nome_ficticio", "turma_codigo"}
    _ok_componente = set(campos_componente) == {"codigo_componente", "nome_componente", "carga_horaria"}
    _ok_pk = chave_primaria_estudante == "codigo_estudante"
    verificar(_ok_estudante and _ok_componente and _ok_pk,
              "Releia os campos: 'turma_codigo' pertence a Estudante (é a FK que liga à Turma), e a PK de Estudante é o código que não se repete.")
else:
    verificar(False, "", ainda_nao_resolvido=True)

📝 Ainda não resolvido — complete o código acima antes de verificar.

## Passo 3 — Cardinalidade dos relacionamentos

**Cardinalidade** indica **quantas** ocorrências de uma entidade podem se relacionar com **quantas** ocorrências de outra entidade. As três cardinalidades mais comuns são:

| Cardinalidade | Significado | Exemplo no nosso cenário escolar |
|---|---|---|
| **1:1** (um para um) | Uma ocorrência de A se relaciona com **no máximo uma** ocorrência de B, e vice-versa. | Um `Estudante` possui **um único** cartão de identificação escolar; cada cartão pertence a **um único** estudante. |
| **1:N** (um para muitos) | Uma ocorrência de A se relaciona com **várias** ocorrências de B, mas cada B se relaciona com **apenas uma** A. | Uma `Turma` possui **vários** `Estudantes`, mas cada `Estudante` pertence a **uma única** `Turma`. |
| **N:N** (muitos para muitos) | Várias ocorrências de A se relacionam com várias ocorrências de B. | Um `Estudante` pode cursar **vários** `Componentes`, e cada `Componente` é cursado por **vários** `Estudantes` (por isso existe a entidade associativa `Matrícula`, que "desmonta" o N:N em dois relacionamentos 1:N). |

> 💬 **Por que a Matrícula existe?** Bancos de dados relacionais não representam diretamente um relacionamento N:N — por isso criamos uma **entidade associativa** (`Matrícula`/`Resultado`) que guarda a combinação `codigo_estudante` + `codigo_componente`, transformando o N:N em dois relacionamentos 1:N.

## Passo 4 — Participação: obrigatória ou opcional?

Além da cardinalidade, cada entidade tem um tipo de **participação** no relacionamento:

- **Participação obrigatória (total)**: toda ocorrência da entidade **precisa** participar do relacionamento. Ex.: toda `Matrícula` **precisa** ter um `Estudante` associado — não existe matrícula "solta".
- **Participação opcional (parcial)**: pode existir uma ocorrência da entidade que **não participa** do relacionamento. Ex.: pode existir um `Estudante` que **ainda não** tem nenhuma `Matrícula` registrada em um componente (por exemplo, acabou de ingressar na escola).

> 🔑 **Conexão direta com o Módulo 2:** é exatamente essa **participação opcional** que vamos explorar com o `LEFT JOIN` — quando queremos listar **todos** os estudantes, mesmo aqueles que ainda **não têm** correspondência na tabela de matrículas/resultados.

### 📖 Glossário simples — Cardinalidade e participação

| Termo | Explicação simples |
|---|---|
| **Cardinalidade 1:1** | Uma ocorrência liga-se a, no máximo, uma outra ocorrência. |
| **Cardinalidade 1:N** | Uma ocorrência liga-se a várias outras, mas cada uma dessas se liga a apenas uma. |
| **Cardinalidade N:N** | Várias ocorrências de um lado se ligam a várias do outro lado. |
| **Entidade associativa** | Tabela criada para "resolver" um relacionamento N:N (ex.: Matrícula). |
| **Participação obrigatória** | Toda ocorrência da entidade precisa estar no relacionamento. |
| **Participação opcional** | A ocorrência pode existir sem participar do relacionamento. |

### ✏️ Exercício 2 — Classificando cardinalidade e participação

Para cada situação abaixo, complete com a cardinalidade (`"1:1"`, `"1:N"` ou `"N:N"`) e a participação (`"obrigatória"` ou `"opcional"`) mais adequada.

1. Uma `Turma` e seus vários `Estudantes` (do ponto de vista da Turma para o Estudante).
2. Um `Estudante` e os vários `Componentes` que ele pode cursar (pensando nos dois lados, sem a entidade associativa).
3. Um `Estudante` recém-matriculado que **ainda não** possui nenhum resultado lançado em `Matrícula`.

**Alternativa sem código:** desenhe três pequenos diagramas com duas caixas ligadas por uma linha, escrevendo a cardinalidade (ex.: "1" e "N") em cada ponta da linha.

In [6]:
# ✏️ Espaço para resposta/código — Exercício 2
cardinalidade_turma_estudante = None   # substitua por "1:N"
cardinalidade_estudante_componente = None  # substitua por "N:N"
participacao_estudante_sem_resultado = None  # substitua por "opcional"

print("Turma-Estudante:", cardinalidade_turma_estudante)
print("Estudante-Componente:", cardinalidade_estudante_componente)
print("Participação do estudante sem resultado:", participacao_estudante_sem_resultado)

Turma-Estudante: None
Estudante-Componente: None
Participação do estudante sem resultado: None

<details>
<summary>🔓 <b>Clique aqui para ver a solução do professor — Exercício 2</b></summary>

```python
cardinalidade_turma_estudante = "1:N"
cardinalidade_estudante_componente = "N:N"
participacao_estudante_sem_resultado = "opcional"
```

**Explicação:** uma Turma tem vários Estudantes, mas cada Estudante está em uma única Turma (1:N). Um Estudante pode cursar vários Componentes e um Componente é cursado por vários Estudantes (N:N). Um estudante sem resultado lançado tem participação **opcional** no relacionamento com Matrícula — ele existe mesmo sem essa ligação.
</details>

In [7]:
# ✅ Verificação automática — Exercício 2
_pendente = (cardinalidade_turma_estudante is None or cardinalidade_estudante_componente is None
             or participacao_estudante_sem_resultado is None)
if not _pendente:
    verificar(cardinalidade_turma_estudante == "1:N"
              and cardinalidade_estudante_componente == "N:N"
              and participacao_estudante_sem_resultado == "opcional",
              "Releia o Passo 3: Turma-Estudante é 1:N; Estudante-Componente (sem entidade associativa) é N:N; quem pode 'não existir' na relação tem participação opcional.")
else:
    verificar(False, "", ainda_nao_resolvido=True)

📝 Ainda não resolvido — complete o código acima antes de verificar.

## Passo 5 — Montando o modelo ER do nosso cenário escolar (atividade de construção)

Agora é sua vez de **construir** um modelo ER simplificado, representando por texto as entidades, atributos, chaves e relacionamentos que usaremos na base de dados desta aula.

**Alternativa sem código (cartão ER):** desenhe 4 caixas (`Turma`, `Estudante`, `Componente`, `Matrícula`) e ligue-as com linhas, escrevendo a cardinalidade em cada ponta:

```
[Turma] --1-----N-- [Estudante] --1-----N-- [Matrícula] --N-----1-- [Componente]
```

In [8]:
# ✏️ Espaço para resposta/código — Exercício 3 (construção do modelo ER em texto)
# Complete o dicionário abaixo descrevendo o relacionamento entre Turma e Estudante

modelo_er_turma_estudante = {
    "entidade_1": "Turma",
    "entidade_2": "Estudante",
    "cardinalidade": None,     # substitua por "1:N"
    "participacao_estudante": None,  # substitua por "obrigatória" (todo estudante pertence a uma turma)
}

print(modelo_er_turma_estudante)

{'entidade_1': 'Turma', 'entidade_2': 'Estudante', 'cardinalidade': None, 'participacao_estudante': None}

<details>
<summary>🔓 <b>Clique aqui para ver a solução do professor — Exercício 3</b></summary>

```python
modelo_er_turma_estudante = {
    "entidade_1": "Turma",
    "entidade_2": "Estudante",
    "cardinalidade": "1:N",
    "participacao_estudante": "obrigatória",
}
```

**Explicação:** consideramos que, neste cenário, todo estudante cadastrado precisa estar vinculado a uma turma (participação obrigatória do lado do Estudante), e cada turma pode ter vários estudantes (cardinalidade 1:N).
</details>

In [9]:
# ✅ Verificação automática — Exercício 3
_pendente = modelo_er_turma_estudante["cardinalidade"] is None or modelo_er_turma_estudante["participacao_estudante"] is None
if not _pendente:
    verificar(modelo_er_turma_estudante["cardinalidade"] == "1:N"
              and modelo_er_turma_estudante["participacao_estudante"] == "obrigatória",
              "Pense: cada turma tem VÁRIOS estudantes (1:N) e, neste cenário, todo estudante PRECISA ter uma turma (obrigatória).")
else:
    verificar(False, "", ainda_nao_resolvido=True)

📝 Ainda não resolvido — complete o código acima antes de verificar.

---
## 🛠️ Construindo nossa base de dados escolar simulada (SQLite)

Agora vamos **colocar o modelo ER em prática**, criando de verdade as tabelas em um banco de dados SQLite — tudo dentro da memória do notebook, sem nenhum arquivo externo.

As tabelas seguem o modelo que estudamos:

- `turmas` — entidade Turma
- `estudantes` — entidade Estudante (identificadores fictícios, sem nomes reais)
- `componentes` — entidade Componente Curricular
- `matriculas` — entidade associativa (resolve o N:N entre Estudante e Componente)

> ⚠️ **Atenção — dados propositalmente incompletos:** para praticarmos o `LEFT JOIN` no Módulo 2, vamos incluir **de propósito**:
> - um estudante **sem nenhuma matrícula/resultado** lançado (participação opcional);
> - uma turma **sem nenhum estudante** vinculado.

In [10]:
# Criando a conexão com um banco de dados SQLite em memória (não gera nenhum arquivo no disco)
conexao = sqlite3.connect(":memory:")
cursor = conexao.cursor()

print("Banco de dados SQLite em memória criado com sucesso!")

Banco de dados SQLite em memória criado com sucesso!

In [11]:
# Criando a tabela TURMAS (entidade Turma)
cursor.execute('''
CREATE TABLE turmas (
    codigo_turma TEXT PRIMARY KEY,
    nome_turma TEXT NOT NULL,
    turno TEXT NOT NULL
)
''')

# Criando a tabela ESTUDANTES (entidade Estudante) — identificadores fictícios, sem nomes reais
cursor.execute('''
CREATE TABLE estudantes (
    codigo_estudante TEXT PRIMARY KEY,
    apelido_ficticio TEXT NOT NULL,
    codigo_turma TEXT,
    FOREIGN KEY (codigo_turma) REFERENCES turmas(codigo_turma)
)
''')

# Criando a tabela COMPONENTES (entidade Componente Curricular)
cursor.execute('''
CREATE TABLE componentes (
    codigo_componente TEXT PRIMARY KEY,
    nome_componente TEXT NOT NULL,
    carga_horaria INTEGER NOT NULL
)
''')

# Criando a tabela MATRICULAS (entidade associativa: liga Estudante e Componente, com o resultado)
cursor.execute('''
CREATE TABLE matriculas (
    codigo_matricula INTEGER PRIMARY KEY AUTOINCREMENT,
    codigo_estudante TEXT NOT NULL,
    codigo_componente TEXT NOT NULL,
    resultado TEXT NOT NULL,
    FOREIGN KEY (codigo_estudante) REFERENCES estudantes(codigo_estudante),
    FOREIGN KEY (codigo_componente) REFERENCES componentes(codigo_componente)
)
''')

conexao.commit()
print("Tabelas criadas: turmas, estudantes, componentes, matriculas")

Tabelas criadas: turmas, estudantes, componentes, matriculas

In [12]:
# Inserindo dados fictícios — TURMAS
# Observe: a turma "T03" (3º módulo, período noturno) será deixada SEM nenhum estudante vinculado (participação opcional)
turmas_ficticias = [
    ("T01", "3ª Série A Técnico", "Noturno"),
    ("T02", "3ª BT", "Matutino"),
    ("T03", "Turma-piloto (sem estudantes ainda)", "Noturno"),
]
cursor.executemany("INSERT INTO turmas VALUES (?, ?, ?)", turmas_ficticias)

# Inserindo dados fictícios — ESTUDANTES (apelidos genéricos, nenhum nome real)
# Observe: "EST010" será um estudante recém-chegado, SEM nenhuma matrícula/resultado ainda
estudantes_ficticios = [
    ("EST001", "Estudante Alfa", "T01"),
    ("EST002", "Estudante Beta", "T01"),
    ("EST003", "Estudante Gama", "T01"),
    ("EST004", "Estudante Delta", "T02"),
    ("EST005", "Estudante Épsilon", "T02"),
    ("EST006", "Estudante Zeta", "T02"),
    ("EST007", "Estudante Eta", "T01"),
    ("EST008", "Estudante Teta", "T02"),
    ("EST009", "Estudante Iota", "T01"),
    ("EST010", "Estudante Capa (recém-chegado)", "T02"),
]
cursor.executemany("INSERT INTO estudantes VALUES (?, ?, ?)", estudantes_ficticios)

# Inserindo dados fictícios — COMPONENTES
componentes_ficticios = [
    ("C01", "Banco de Dados e Computação em Nuvem", 80),
    ("C02", "Programação Aplicada", 120),
    ("C03", "Matemática e Estatística para Ciência de Dados", 80),
    ("C04", "Aprendizagem de Máquina", 80),
]
cursor.executemany("INSERT INTO componentes VALUES (?, ?, ?)", componentes_ficticios)

conexao.commit()
print("Dados inseridos em turmas, estudantes e componentes.")

Dados inseridos em turmas, estudantes e componentes.

In [13]:
# Inserindo dados fictícios — MATRICULAS (resultados)
# Observe: EST010 propositalmente NÃO aparece aqui (sem correspondência) — vamos usar isso no LEFT JOIN
matriculas_ficticias = [
    ("EST001", "C01", "Aprovado"),
    ("EST001", "C02", "Aprovado"),
    ("EST002", "C01", "Em recuperação"),
    ("EST002", "C03", "Aprovado"),
    ("EST003", "C01", "Aprovado"),
    ("EST004", "C01", "Aprovado"),
    ("EST004", "C04", "Aprovado"),
    ("EST005", "C01", "Em recuperação"),
    ("EST006", "C02", "Aprovado"),
    ("EST007", "C01", "Aprovado"),
    ("EST007", "C03", "Em recuperação"),
    ("EST008", "C01", "Aprovado"),
    ("EST009", "C04", "Aprovado"),
    # EST010 não possui nenhuma linha aqui — participação opcional, sem correspondência
]
cursor.executemany(
    "INSERT INTO matriculas (codigo_estudante, codigo_componente, resultado) VALUES (?, ?, ?)",
    matriculas_ficticias
)

conexao.commit()
print("Dados inseridos em matriculas. Total de registros:", len(matriculas_ficticias))
print("Lembrete: EST010 e a turma T03 foram deixados propositalmente sem correspondência.")

Dados inseridos em matriculas. Total de registros: 13
Lembrete: EST010 e a turma T03 foram deixados propositalmente sem correspondência.

### 👀 Conferindo as tabelas criadas

Vamos usar `pandas.read_sql_query` para visualizar cada tabela como um DataFrame — assim fica mais fácil de ler.

In [14]:
# Visualizando a tabela TURMAS
df_turmas = pd.read_sql_query("SELECT * FROM turmas", conexao)
df_turmas

  codigo_turma                           nome_turma     turno
0          T01                   3ª Série A Técnico   Noturno
1          T02                                3ª BT  Matutino
2          T03  Turma-piloto (sem estudantes ainda)   Noturno

In [15]:
# Visualizando a tabela ESTUDANTES
df_estudantes = pd.read_sql_query("SELECT * FROM estudantes", conexao)
df_estudantes

  codigo_estudante                apelido_ficticio codigo_turma
0           EST001                  Estudante Alfa          T01
1           EST002                  Estudante Beta          T01
2           EST003                  Estudante Gama          T01
3           EST004                 Estudante Delta          T02
4           EST005               Estudante Épsilon          T02
5           EST006                  Estudante Zeta          T02
6           EST007                   Estudante Eta          T01
7           EST008                  Estudante Teta          T02
8           EST009                  Estudante Iota          T01
9           EST010  Estudante Capa (recém-chegado)          T02

In [16]:
# Visualizando a tabela COMPONENTES
df_componentes = pd.read_sql_query("SELECT * FROM componentes", conexao)
df_componentes

  codigo_componente                                 nome_componente  carga_horaria
0               C01            Banco de Dados e Computação em Nuvem             80
1               C02                            Programação Aplicada            120
2               C03  Matemática e Estatística para Ciência de Dados             80
3               C04                         Aprendizagem de Máquina             80

In [17]:
# Visualizando a tabela MATRICULAS
df_matriculas = pd.read_sql_query("SELECT * FROM matriculas", conexao)
df_matriculas

    codigo_matricula codigo_estudante codigo_componente       resultado
0                  1           EST001               C01        Aprovado
1                  2           EST001               C02        Aprovado
2                  3           EST002               C01  Em recuperação
3                  4           EST002               C03        Aprovado
4                  5           EST003               C01        Aprovado
5                  6           EST004               C01        Aprovado
6                  7           EST004               C04        Aprovado
7                  8           EST005               C01  Em recuperação
8                  9           EST006               C02        Aprovado
9                 10           EST007               C01        Aprovado
10                11           EST007               C03  Em recuperação
11                12           EST008               C01        Aprovado
12                13           EST009               C04        Aprovado

---
# 🟩 AULA 2 (EEBFM) / AULA 2 (EEJC) — Módulo 2: Junções Externas (LEFT JOIN)

**Defasagem trabalhada:** recuperar dados mesmo quando não há correspondência entre tabelas.

## Passo 1 — Relembrando o `INNER JOIN`

O `INNER JOIN` (junção interna) retorna **apenas as linhas que têm correspondência em ambas as tabelas**. Se um estudante não tem nenhuma matrícula, ele **não aparece** no resultado.

Vamos ver isso na prática: uma consulta juntando `estudantes` e `matriculas` usando `INNER JOIN`.

In [18]:
# Consulta com INNER JOIN — só aparecem estudantes que têm ao menos uma matrícula
consulta_inner = '''
SELECT
    estudantes.codigo_estudante,
    estudantes.apelido_ficticio,
    matriculas.codigo_componente,
    matriculas.resultado
FROM estudantes
INNER JOIN matriculas ON estudantes.codigo_estudante = matriculas.codigo_estudante
ORDER BY estudantes.codigo_estudante
'''

resultado_inner = pd.read_sql_query(consulta_inner, conexao)
print("Quantidade de linhas no resultado do INNER JOIN:", len(resultado_inner))
resultado_inner

Quantidade de linhas no resultado do INNER JOIN: 13

   codigo_estudante   apelido_ficticio codigo_componente       resultado
0            EST001     Estudante Alfa               C01        Aprovado
1            EST001     Estudante Alfa               C02        Aprovado
2            EST002     Estudante Beta               C01  Em recuperação
3            EST002     Estudante Beta               C03        Aprovado
4            EST003     Estudante Gama               C01        Aprovado
5            EST004    Estudante Delta               C01        Aprovado
6            EST004    Estudante Delta               C04        Aprovado
7            EST005  Estudante Épsilon               C01  Em recuperação
8            EST006     Estudante Zeta               C02        Aprovado
9            EST007      Estudante Eta               C01        Aprovado
10           EST007      Estudante Eta               C03  Em recuperação
11           EST008     Estudante Teta               C01        Aprovado
12           EST009     Estudante Iota               C04        Aprovado

## Passo 2 — O que é uma junção externa (`LEFT JOIN`)?

Uma **junção externa** (*outer join*) é usada quando queremos manter **todas** as linhas de uma tabela, **mesmo que não haja correspondência** na outra tabela. No SQLite, a forma mais usada e mais compatível é o `LEFT JOIN` (junção externa à esquerda):

- `LEFT JOIN` mantém **todas as linhas da tabela à esquerda** (a primeira mencionada no `FROM`), preenchendo com `NULL` (nulo) as colunas da tabela à direita quando **não há correspondência**.

> ⚠️ **Nota técnica importante:** o padrão SQL também define `RIGHT JOIN` (junção externa à direita) e `FULL JOIN` (junção externa completa), mas **esses comandos têm diferenças de suporte entre os SGBDs**. O SQLite, por exemplo, historicamente **não oferecia suporte nativo a `RIGHT JOIN`/`FULL JOIN`** (isso vem mudando em versões recentes, mas o suporte não é universal). Por isso, **neste notebook focamos no `LEFT JOIN`**, que funciona de forma consistente em praticamente todos os SGBDs, incluindo o SQLite. Na prática, um `RIGHT JOIN` pode sempre ser reescrito como um `LEFT JOIN` apenas invertendo a ordem das tabelas.

## Passo 3 — Comparando `INNER JOIN` e `LEFT JOIN` na prática

Vamos repetir a mesma consulta do Passo 1, mas agora usando `LEFT JOIN`.

In [19]:
# Consulta com LEFT JOIN — mantém TODOS os estudantes, mesmo sem matrícula correspondente
consulta_left = '''
SELECT
    estudantes.codigo_estudante,
    estudantes.apelido_ficticio,
    matriculas.codigo_componente,
    matriculas.resultado
FROM estudantes
LEFT JOIN matriculas ON estudantes.codigo_estudante = matriculas.codigo_estudante
ORDER BY estudantes.codigo_estudante
'''

resultado_left = pd.read_sql_query(consulta_left, conexao)
print("Quantidade de linhas no resultado do LEFT JOIN:", len(resultado_left))
resultado_left

Quantidade de linhas no resultado do LEFT JOIN: 14

   codigo_estudante                apelido_ficticio codigo_componente       resultado
0            EST001                  Estudante Alfa               C01        Aprovado
1            EST001                  Estudante Alfa               C02        Aprovado
2            EST002                  Estudante Beta               C01  Em recuperação
3            EST002                  Estudante Beta               C03        Aprovado
4            EST003                  Estudante Gama               C01        Aprovado
5            EST004                 Estudante Delta               C01        Aprovado
6            EST004                 Estudante Delta               C04        Aprovado
7            EST005               Estudante Épsilon               C01  Em recuperação
8            EST006                  Estudante Zeta               C02        Aprovado
9            EST007                   Estudante Eta               C01        Aprovado
10           EST007                   Estudante Eta               C03  Em recuperação
11           EST008                  Estudante Teta               C01        Aprovado
12           EST009                  Estudante Iota               C04        Aprovado
13           EST010  Estudante Capa (recém-chegado)               NaN             NaN

## Passo 4 — Identificando os registros sem correspondência

Repare que o `EST010` aparece no resultado do `LEFT JOIN`, mas com `None`/`NaN` nas colunas de `matriculas` — isso mostra visualmente que ele **não tem nenhuma matrícula** cadastrada ainda.

Podemos filtrar exatamente essas linhas usando `WHERE ... IS NULL` no SQL, ou o método `.isna()` do pandas.

In [20]:
# Filtrando, via SQL, os estudantes SEM nenhuma matrícula correspondente
consulta_sem_matricula = '''
SELECT
    estudantes.codigo_estudante,
    estudantes.apelido_ficticio
FROM estudantes
LEFT JOIN matriculas ON estudantes.codigo_estudante = matriculas.codigo_estudante
WHERE matriculas.codigo_matricula IS NULL
'''

resultado_sem_matricula = pd.read_sql_query(consulta_sem_matricula, conexao)
print("Estudantes sem nenhuma matrícula registrada:")
resultado_sem_matricula

Estudantes sem nenhuma matrícula registrada:

  codigo_estudante                apelido_ficticio
0           EST010  Estudante Capa (recém-chegado)

## Passo 5 — Comparação visual dos resultados

| Aspecto | `INNER JOIN` | `LEFT JOIN` |
|---|---|---|
| **Linhas retornadas** | Só as que têm correspondência nas duas tabelas | Todas da tabela à esquerda, mesmo sem correspondência |
| **Valores sem par** | Não aparecem | Aparecem como `NULL`/`NaN` |
| **Uso típico** | "Quero só quem realmente tem X" | "Quero todos, e quero ENXERGAR quem não tem X" |
| **Neste exemplo** | 13 linhas (sem `EST010`) | 14 linhas (`EST010` aparece com valores nulos) |

> 💬 **Pergunta para reflexão:** em qual situação da escola faria mais sentido usar `LEFT JOIN` em vez de `INNER JOIN`? (ex.: relatório para identificar quem **ainda não** fez uma prova, quem **ainda não** entregou um trabalho...)

### 📖 Glossário simples — Módulo 2

| Termo | Explicação simples |
|---|---|
| **JOIN** | Comando SQL que combina linhas de duas (ou mais) tabelas com base em uma condição. |
| **INNER JOIN** | Só retorna linhas que existem em ambas as tabelas. |
| **LEFT JOIN (junção externa)** | Retorna todas as linhas da tabela à esquerda, mesmo sem correspondência na tabela à direita. |
| **NULL** | Valor "vazio"/desconhecido, usado quando não há correspondência. |
| **Tabela à esquerda** | A primeira tabela citada, logo após o `FROM`. |

### ✏️ Exercício 4 — Turmas sem estudantes (LEFT JOIN)

Complete a consulta abaixo para descobrir se existe alguma **turma sem nenhum estudante vinculado**, usando `LEFT JOIN` entre `turmas` e `estudantes`.

**Dica:** o `FROM` deve começar por `turmas` (tabela à esquerda), e o filtro deve usar `WHERE estudantes.codigo_estudante IS NULL`.

**Alternativa sem código:** observando a tabela `df_turmas` e `df_estudantes` exibidas acima, qual código de turma você acha que **não aparece** na coluna `codigo_turma` de nenhum estudante?

In [21]:
# ✏️ Espaço para resposta/código — Exercício 4 (consulta parcialmente preenchida)
consulta_turmas_sem_estudantes = '''
SELECT
    turmas.codigo_turma,
    turmas.nome_turma
FROM turmas
___ JOIN estudantes ON turmas.codigo_turma = estudantes.codigo_turma
WHERE estudantes.codigo_estudante IS ___
'''
# Substitua os dois "___" acima: o tipo de junção (LEFT) e a palavra-chave de valor ausente (NULL)

resultado_turmas_sem_estudantes = None  # substitua por pd.read_sql_query(consulta_turmas_sem_estudantes, conexao)
resultado_turmas_sem_estudantes

<details>
<summary>🔓 <b>Clique aqui para ver a solução do professor — Exercício 4</b></summary>

```python
consulta_turmas_sem_estudantes = '''
SELECT
    turmas.codigo_turma,
    turmas.nome_turma
FROM turmas
LEFT JOIN estudantes ON turmas.codigo_turma = estudantes.codigo_turma
WHERE estudantes.codigo_estudante IS NULL
'''

resultado_turmas_sem_estudantes = pd.read_sql_query(consulta_turmas_sem_estudantes, conexao)
```

**Explicação:** o `LEFT JOIN` mantém todas as turmas, mesmo sem estudante correspondente; o filtro `IS NULL` seleciona apenas as turmas que ficaram "sem par" — neste caso, a `T03`.
</details>

In [22]:
# ✅ Verificação automática — Exercício 4
_pendente = resultado_turmas_sem_estudantes is None
if not _pendente:
    _esperado = pd.read_sql_query('''
        SELECT turmas.codigo_turma, turmas.nome_turma
        FROM turmas
        LEFT JOIN estudantes ON turmas.codigo_turma = estudantes.codigo_turma
        WHERE estudantes.codigo_estudante IS NULL
    ''', conexao)
    _ok = list(resultado_turmas_sem_estudantes["codigo_turma"]) == list(_esperado["codigo_turma"])
    verificar(_ok, "Confira se você usou LEFT JOIN (não INNER JOIN) e o filtro IS NULL na coluna codigo_estudante.")
else:
    verificar(False, "", ainda_nao_resolvido=True)

📝 Ainda não resolvido — complete o código acima antes de verificar.

### ✏️ Exercício 5 — Contando quantos estudantes cada turma tem (incluindo zero)

Complete a consulta abaixo para contar quantos estudantes existem em cada turma, garantindo que a `T03` apareça com contagem **zero**, e não fique de fora do resultado.

**Dica:** use `LEFT JOIN`, `GROUP BY turmas.codigo_turma` e `COUNT(estudantes.codigo_estudante)` (o `COUNT` de uma coluna ignora os `NULL`s, então uma turma sem estudante conta como 0).

In [23]:
# ✏️ Espaço para resposta/código — Exercício 5
consulta_contagem_turma = '''
SELECT
    turmas.codigo_turma,
    turmas.nome_turma,
    COUNT(estudantes.codigo_estudante) AS total_estudantes
FROM turmas
LEFT JOIN estudantes ON turmas.codigo_turma = estudantes.codigo_turma
GROUP BY ___
ORDER BY turmas.codigo_turma
'''
# Substitua o "___" pelo campo de agrupamento correto

resultado_contagem_turma = None  # substitua por pd.read_sql_query(consulta_contagem_turma, conexao)
resultado_contagem_turma

<details>
<summary>🔓 <b>Clique aqui para ver a solução do professor — Exercício 5</b></summary>

```python
consulta_contagem_turma = '''
SELECT
    turmas.codigo_turma,
    turmas.nome_turma,
    COUNT(estudantes.codigo_estudante) AS total_estudantes
FROM turmas
LEFT JOIN estudantes ON turmas.codigo_turma = estudantes.codigo_turma
GROUP BY turmas.codigo_turma
ORDER BY turmas.codigo_turma
'''

resultado_contagem_turma = pd.read_sql_query(consulta_contagem_turma, conexao)
```

**Explicação:** o agrupamento deve ser feito por `turmas.codigo_turma` (o identificador da turma). Como usamos `LEFT JOIN`, a `T03` aparece no resultado com `total_estudantes = 0`.
</details>

In [24]:
# ✅ Verificação automática — Exercício 5
_pendente = resultado_contagem_turma is None
if not _pendente:
    _esperado = pd.read_sql_query('''
        SELECT turmas.codigo_turma, COUNT(estudantes.codigo_estudante) AS total_estudantes
        FROM turmas
        LEFT JOIN estudantes ON turmas.codigo_turma = estudantes.codigo_turma
        GROUP BY turmas.codigo_turma
        ORDER BY turmas.codigo_turma
    ''', conexao)
    _comp = resultado_contagem_turma[["codigo_turma", "total_estudantes"]].reset_index(drop=True)
    _ok = _comp.equals(_esperado.reset_index(drop=True))
    _tem_t03_zero = ((resultado_contagem_turma["codigo_turma"] == "T03") &
                      (resultado_contagem_turma["total_estudantes"] == 0)).any()
    verificar(_ok and _tem_t03_zero, "Confira o GROUP BY (deve ser por turmas.codigo_turma) e se a T03 aparece com total_estudantes = 0.")
else:
    verificar(False, "", ainda_nao_resolvido=True)

📝 Ainda não resolvido — complete o código acima antes de verificar.

---
# 🟨 AULA 3 (EEJC) — Módulo 3: Junções Múltiplas (três ou mais tabelas)

*(Na EEBFM, este módulo é trabalhado na mesma Aula 2, logo em seguida ao Módulo 2, de forma integrada.)*

**Defasagem trabalhada:** elaborar consultas combinando mais de duas tabelas.

## Passo 1 — Por que juntar mais de duas tabelas?

Em situações reais, a informação que queremos **não está toda em uma única tabela** — ela está espalhada em várias. Por exemplo, para responder "qual o **nome do componente** e o **resultado** de cada **estudante**, junto com o **nome da turma** dele?", precisamos combinar **quatro** tabelas: `estudantes`, `turmas`, `matriculas` e `componentes`.

## Passo 2 — Usando aliases (apelidos de tabela)

Quando o número de tabelas aumenta, os nomes completos (`estudantes.codigo_estudante`) deixam a consulta longa. Por isso, usamos **aliases** (apelidos curtos) para cada tabela, definidos logo após o nome dela no `FROM`/`JOIN`:

```sql
FROM estudantes AS e
JOIN turmas AS t ON e.codigo_turma = t.codigo_turma
```

A partir daí, usamos `e.` e `t.` no lugar dos nomes completos.

## Passo 3 — Encadeando múltiplos `JOIN`s

Uma junção múltipla nada mais é do que **vários `JOIN`s em sequência**, cada um ligando um novo par de tabelas.

In [25]:
# Consulta com JUNÇÃO MÚLTIPLA — combina estudantes, turmas, matriculas e componentes (4 tabelas)
consulta_multipla = '''
SELECT
    e.codigo_estudante,
    e.apelido_ficticio,
    t.nome_turma,
    c.nome_componente,
    m.resultado
FROM estudantes AS e
JOIN turmas AS t ON e.codigo_turma = t.codigo_turma
JOIN matriculas AS m ON e.codigo_estudante = m.codigo_estudante
JOIN componentes AS c ON m.codigo_componente = c.codigo_componente
ORDER BY t.nome_turma, e.codigo_estudante, c.nome_componente
'''

resultado_multiplo = pd.read_sql_query(consulta_multipla, conexao)
print("Total de linhas no resultado:", len(resultado_multiplo))
resultado_multiplo

Total de linhas no resultado: 13

,codigo_estudante,apelido_ficticio,nome_turma,nome_componente,resultado
0,EST004,Estudante Delta,3ª BT,Aprendizagem de Máquina,Aprovado
1,EST004,Estudante Delta,3ª BT,Banco de Dados e Computação em Nuvem,Aprovado
2,EST005,Estudante Épsilon,3ª BT,Banco de Dados e Computação em Nuvem,Em recuperação
3,EST006,Estudante Zeta,3ª BT,Programação Aplicada,Aprovado
4,EST008,Estudante Teta,3ª BT,Banco de Dados e Computação em Nuvem,Aprovado
5,EST001,Estudante Alfa,3ª Série A Técnico,Banco de Dados e Computação em Nuvem,Aprovado
6,EST001,Estudante Alfa,3ª Série A Técnico,Programação Aplicada,Aprovado
7,EST002,Estudante Beta,3ª Série A Técnico,Banco de Dados e Computação em Nuvem,Em recuperação
8,EST002,Estudante Beta,3ª Série A Técnico,Matemática e Estatística para Ciência de Dados,Aprovado
9,EST003,Estudante Gama,3ª Série A Técnico,Banco de Dados e Computação em Nuvem,Aprovado
10,EST007,Estudante Eta,3ª Série A Técnico,Banco de Dados e Computação em Nuvem,Aprovado
11,EST007,Estudante Eta,3ª Série A Técnico,Matemática e Estatística para Ciência de Dados,Em recuperação
12,EST009,Estudante Iota,3ª Série A Técnico,Aprendizagem de Máquina,Aprovado

> 💬 Repare que usamos `JOIN` (equivalente a `INNER JOIN`) entre `estudantes`/`matriculas`/`componentes`, pois aqui queremos apenas quem **realmente tem** matrícula. Se quiséssemos manter também o `EST010` (sem matrícula) neste relatório combinado, trocaríamos o `JOIN` com `matriculas` por `LEFT JOIN` — os dois conceitos (Módulo 2 e Módulo 3) podem ser **combinados**!

## Passo 4 — Selecionando colunas específicas e ordenando o resultado

Em uma junção múltipla, é comum **selecionar apenas as colunas necessárias** (em vez de `SELECT *`) e **ordenar** o resultado com `ORDER BY` para facilitar a leitura — como já fizemos acima, ordenando por turma, depois por estudante, depois por componente.

In [26]:
# Exemplo: junção múltipla combinando LEFT JOIN (Módulo 2) + múltiplas tabelas (Módulo 3)
# Mantém TODOS os estudantes (mesmo sem matrícula), combinando com turma e, quando existir, componente/resultado
consulta_multipla_com_left = '''
SELECT
    e.codigo_estudante,
    e.apelido_ficticio,
    t.nome_turma,
    c.nome_componente,
    m.resultado
FROM estudantes AS e
JOIN turmas AS t ON e.codigo_turma = t.codigo_turma
LEFT JOIN matriculas AS m ON e.codigo_estudante = m.codigo_estudante
LEFT JOIN componentes AS c ON m.codigo_componente = c.codigo_componente
ORDER BY t.nome_turma, e.codigo_estudante
'''

resultado_multiplo_left = pd.read_sql_query(consulta_multipla_com_left, conexao)
print("Total de linhas (deve incluir EST010 com valores nulos):", len(resultado_multiplo_left))
resultado_multiplo_left[resultado_multiplo_left["codigo_estudante"] == "EST010"]

Total de linhas (deve incluir EST010 com valores nulos): 14

  codigo_estudante                apelido_ficticio nome_turma nome_componente resultado
5           EST010  Estudante Capa (recém-chegado)      3ª BT             NaN       NaN

### 📖 Glossário simples — Módulo 3

| Termo | Explicação simples |
|---|---|
| **Junção múltipla** | Consulta que combina três ou mais tabelas usando vários `JOIN`s em sequência. |
| **Alias (apelido de tabela)** | Nome curto dado a uma tabela (ex.: `AS e`) para simplificar a escrita da consulta. |
| **ORDER BY** | Cláusula que define a ordem de exibição das linhas do resultado. |
| **SELECT (colunas específicas)** | Escolher apenas as colunas necessárias, em vez de trazer todas com `*`. |

### ✏️ Exercício 6 — Completando uma junção de três tabelas

Complete a consulta abaixo para listar, para cada matrícula: o **apelido do estudante**, o **nome do componente** e o **resultado**, combinando as tabelas `estudantes`, `matriculas` e `componentes` (três tabelas). Use os aliases `e`, `m` e `c`.

**Alternativa sem código:** em uma tabela de papel com três colunas (Estudante, Componente, Resultado), preencha manualmente cruzando as informações de `df_estudantes`, `df_matriculas` e `df_componentes` mostradas anteriormente, para os 3 primeiros registros de `matriculas`.

In [27]:
# ✏️ Espaço para resposta/código — Exercício 6 (consulta parcialmente preenchida)
consulta_exercicio6 = '''
SELECT
    e.apelido_ficticio,
    c.nome_componente,
    m.resultado
FROM estudantes AS e
JOIN ___ AS m ON e.codigo_estudante = m.codigo_estudante
JOIN componentes AS ___ ON m.codigo_componente = c.codigo_componente
ORDER BY e.apelido_ficticio
'''
# Substitua os dois "___": o nome da tabela de matrículas, e o alias da tabela componentes

resultado_exercicio6 = None  # substitua por pd.read_sql_query(consulta_exercicio6, conexao)
resultado_exercicio6

<details>
<summary>🔓 <b>Clique aqui para ver a solução do professor — Exercício 6</b></summary>

```python
consulta_exercicio6 = '''
SELECT
    e.apelido_ficticio,
    c.nome_componente,
    m.resultado
FROM estudantes AS e
JOIN matriculas AS m ON e.codigo_estudante = m.codigo_estudante
JOIN componentes AS c ON m.codigo_componente = c.codigo_componente
ORDER BY e.apelido_ficticio
'''

resultado_exercicio6 = pd.read_sql_query(consulta_exercicio6, conexao)
```

**Explicação:** a tabela que liga estudante e componente é `matriculas` (apelidada de `m`), e o alias da tabela `componentes` usado no `SELECT` (`c.nome_componente`) precisa ser `c`.
</details>

In [28]:
# ✅ Verificação automática — Exercício 6
_pendente = resultado_exercicio6 is None
if not _pendente:
    _esperado = pd.read_sql_query('''
        SELECT e.apelido_ficticio, c.nome_componente, m.resultado
        FROM estudantes AS e
        JOIN matriculas AS m ON e.codigo_estudante = m.codigo_estudante
        JOIN componentes AS c ON m.codigo_componente = c.codigo_componente
        ORDER BY e.apelido_ficticio
    ''', conexao)
    _ok = resultado_exercicio6.reset_index(drop=True).equals(_esperado.reset_index(drop=True))
    verificar(_ok, "Confira os aliases: a tabela de ligação é 'matriculas AS m' e o alias de 'componentes' deve ser 'c'.")
else:
    verificar(False, "", ainda_nao_resolvido=True)

📝 Ainda não resolvido — complete o código acima antes de verificar.

### ✏️ Exercício 7 — Junção múltipla com filtro e ordenação

Escreva (do zero, ou adaptando os exemplos anteriores) uma consulta que combine `estudantes`, `turmas` e `matriculas` para listar **apenas os estudantes da turma "T02"** que estão **"Em recuperação"** em algum componente, mostrando `apelido_ficticio`, `nome_turma` e `resultado`, ordenados por `apelido_ficticio`.

**Dica:** use `WHERE t.nome_turma = '3ª BT' ` ou `WHERE t.codigo_turma = 'T02'` combinado com `AND m.resultado = 'Em recuperação'`.

In [29]:
# ✏️ Espaço para resposta/código — Exercício 7 (escreva a consulta completa)
consulta_exercicio7 = None  # substitua por uma string com sua consulta SQL

resultado_exercicio7 = None  # substitua por pd.read_sql_query(consulta_exercicio7, conexao)
resultado_exercicio7

<details>
<summary>🔓 <b>Clique aqui para ver a solução do professor — Exercício 7</b></summary>

```python
consulta_exercicio7 = '''
SELECT
    e.apelido_ficticio,
    t.nome_turma,
    m.resultado
FROM estudantes AS e
JOIN turmas AS t ON e.codigo_turma = t.codigo_turma
JOIN matriculas AS m ON e.codigo_estudante = m.codigo_estudante
WHERE t.codigo_turma = 'T02' AND m.resultado = 'Em recuperação'
ORDER BY e.apelido_ficticio
'''

resultado_exercicio7 = pd.read_sql_query(consulta_exercicio7, conexao)
```

**Explicação:** combinamos três tabelas com `JOIN`, filtramos pela turma `T02` e pelo resultado `'Em recuperação'`, e ordenamos pelo apelido do estudante.
</details>

In [30]:
# ✅ Verificação automática — Exercício 7
_pendente = resultado_exercicio7 is None
if not _pendente:
    _esperado = pd.read_sql_query('''
        SELECT e.apelido_ficticio, t.nome_turma, m.resultado
        FROM estudantes AS e
        JOIN turmas AS t ON e.codigo_turma = t.codigo_turma
        JOIN matriculas AS m ON e.codigo_estudante = m.codigo_estudante
        WHERE t.codigo_turma = 'T02' AND m.resultado = 'Em recuperação'
        ORDER BY e.apelido_ficticio
    ''', conexao)
    _cols = ["apelido_ficticio", "resultado"]
    _ok = (resultado_exercicio7[_cols].reset_index(drop=True).equals(_esperado[_cols].reset_index(drop=True))
           and len(resultado_exercicio7) == len(_esperado) and len(_esperado) > 0)
    verificar(_ok, "Confira o filtro (turma T02 e resultado 'Em recuperação') e se todas as três tabelas foram unidas corretamente.")
else:
    verificar(False, "", ainda_nao_resolvido=True)

📝 Ainda não resolvido — complete o código acima antes de verificar.

---
## 🏆 Desafio final integrador — Modelagem + Consulta de três tabelas

Neste desafio, você vai **primeiro modelar** e **depois consultar** um novo cenário fictício: um **clube de programação** da escola, com **oficinas** e **participantes**.

**Contexto fictício:**
- Uma `oficina` tem um código, um nome e uma carga horária.
- Um `participante` (identificador fictício) pode se inscrever em várias oficinas.
- A tabela `inscricoes` liga `participante` e `oficina`, registrando a `frequencia` (em %).
- Um dos participantes fictícios **ainda não se inscreveu** em nenhuma oficina (participação opcional).

### Parte A — Modelagem (responda em texto)

Complete o dicionário abaixo descrevendo o modelo conceitual do cenário do clube de programação.

In [31]:
# Dados fictícios do desafio final integrador — Clube de Programação
cursor.execute('''
CREATE TABLE oficinas (
    codigo_oficina TEXT PRIMARY KEY,
    nome_oficina TEXT NOT NULL,
    carga_horaria INTEGER NOT NULL
)
''')

cursor.execute('''
CREATE TABLE participantes (
    codigo_participante TEXT PRIMARY KEY,
    apelido_ficticio TEXT NOT NULL
)
''')

cursor.execute('''
CREATE TABLE inscricoes (
    codigo_inscricao INTEGER PRIMARY KEY AUTOINCREMENT,
    codigo_participante TEXT NOT NULL,
    codigo_oficina TEXT NOT NULL,
    frequencia_percentual INTEGER NOT NULL,
    FOREIGN KEY (codigo_participante) REFERENCES participantes(codigo_participante),
    FOREIGN KEY (codigo_oficina) REFERENCES oficinas(codigo_oficina)
)
''')

cursor.executemany("INSERT INTO oficinas VALUES (?, ?, ?)", [
    ("O01", "Python para Iniciantes", 20),
    ("O02", "Banco de Dados na Prática", 20),
    ("O03", "Robótica Educacional", 30),
])

cursor.executemany("INSERT INTO participantes VALUES (?, ?)", [
    ("P01", "Participante Um"),
    ("P02", "Participante Dois"),
    ("P03", "Participante Três"),
    ("P04", "Participante Quatro (sem inscrição ainda)"),
])

cursor.executemany(
    "INSERT INTO inscricoes (codigo_participante, codigo_oficina, frequencia_percentual) VALUES (?, ?, ?)",
    [
        ("P01", "O01", 90),
        ("P01", "O02", 85),
        ("P02", "O02", 70),
        ("P03", "O01", 95),
        ("P03", "O03", 60),
        # P04 não possui nenhuma inscrição — participação opcional, propositalmente sem correspondência
    ]
)

conexao.commit()
print("Base do Clube de Programação criada: oficinas, participantes, inscricoes.")

Base do Clube de Programação criada: oficinas, participantes, inscricoes.

In [32]:
# ✏️ Espaço para resposta/código — Desafio final, Parte A (modelagem)
modelo_desafio_final = {
    "entidades": None,  # substitua por uma lista, ex.: ["Oficina", "Participante", "Inscrição"]
    "cardinalidade_participante_oficina": None,  # substitua por "N:N"
    "participacao_participante_sem_inscricao": None,  # substitua por "opcional"
}

print(modelo_desafio_final)

{'entidades': None, 'cardinalidade_participante_oficina': None, 'participacao_participante_sem_inscricao': None}

<details>
<summary>🔓 <b>Clique aqui para ver a solução do professor — Desafio final, Parte A</b></summary>

```python
modelo_desafio_final = {
    "entidades": ["Oficina", "Participante", "Inscrição"],
    "cardinalidade_participante_oficina": "N:N",
    "participacao_participante_sem_inscricao": "opcional",
}
```

**Explicação:** um participante pode se inscrever em várias oficinas e uma oficina pode ter vários participantes (N:N), resolvido pela entidade associativa `Inscrição`. Um participante pode existir sem nenhuma inscrição (participação opcional).
</details>

In [33]:
# ✅ Verificação automática — Desafio final, Parte A
_pendente = (modelo_desafio_final["entidades"] is None
             or modelo_desafio_final["cardinalidade_participante_oficina"] is None
             or modelo_desafio_final["participacao_participante_sem_inscricao"] is None)
if not _pendente:
    _ok = (set(modelo_desafio_final["entidades"]) == {"Oficina", "Participante", "Inscrição"}
           and modelo_desafio_final["cardinalidade_participante_oficina"] == "N:N"
           and modelo_desafio_final["participacao_participante_sem_inscricao"] == "opcional")
    verificar(_ok, "Releia o contexto: são 3 entidades (Oficina, Participante, Inscrição); a cardinalidade é N:N; e quem pode faltar na relação tem participação opcional.")
else:
    verificar(False, "", ainda_nao_resolvido=True)

📝 Ainda não resolvido — complete o código acima antes de verificar.

### Parte B — Consulta de três tabelas (com junção externa)

Escreva uma consulta que combine `participantes`, `inscricoes` e `oficinas`, mantendo **todos os participantes** (mesmo o `P04`, sem inscrição), mostrando `apelido_ficticio`, `nome_oficina` e `frequencia_percentual`, ordenados por `apelido_ficticio`.

**Dica:** use `LEFT JOIN` a partir de `participantes`.

In [34]:
# ✏️ Espaço para resposta/código — Desafio final, Parte B
consulta_desafio_final = None  # substitua por uma string com sua consulta SQL usando LEFT JOIN

resultado_desafio_final = None  # substitua por pd.read_sql_query(consulta_desafio_final, conexao)
resultado_desafio_final

<details>
<summary>🔓 <b>Clique aqui para ver a solução do professor — Desafio final, Parte B</b></summary>

```python
consulta_desafio_final = '''
SELECT
    p.apelido_ficticio,
    o.nome_oficina,
    i.frequencia_percentual
FROM participantes AS p
LEFT JOIN inscricoes AS i ON p.codigo_participante = i.codigo_participante
LEFT JOIN oficinas AS o ON i.codigo_oficina = o.codigo_oficina
ORDER BY p.apelido_ficticio
'''

resultado_desafio_final = pd.read_sql_query(consulta_desafio_final, conexao)
```

**Explicação:** partindo de `participantes` (tabela à esquerda) com dois `LEFT JOIN`s em sequência (uma junção múltipla), garantimos que `P04` apareça no resultado, mesmo sem oficina/frequência (valores nulos).
</details>

In [35]:
# ✅ Verificação automática — Desafio final, Parte B
_pendente = resultado_desafio_final is None
if not _pendente:
    _esperado = pd.read_sql_query('''
        SELECT p.apelido_ficticio, o.nome_oficina, i.frequencia_percentual
        FROM participantes AS p
        LEFT JOIN inscricoes AS i ON p.codigo_participante = i.codigo_participante
        LEFT JOIN oficinas AS o ON i.codigo_oficina = o.codigo_oficina
        ORDER BY p.apelido_ficticio
    ''', conexao)
    _ok_tamanho = len(resultado_desafio_final) == len(_esperado)
    _tem_p04 = (resultado_desafio_final["apelido_ficticio"] == "Participante Quatro (sem inscrição ainda)").any()
    verificar(_ok_tamanho and _tem_p04, "Use LEFT JOIN (não INNER JOIN) a partir de participantes, para que P04 apareça mesmo sem inscrição.")
else:
    verificar(False, "", ainda_nao_resolvido=True)

📝 Ainda não resolvido — complete o código acima antes de verificar.

---
## 🚀 Atividade de aprofundamento (para quem quiser ir além)

**Pergunta de investigação:** qual é a **frequência média** de cada oficina, considerando apenas quem está inscrito? E qual oficina teve a **maior média**?

**Tarefa:**
1. Escreva uma consulta com junção múltipla entre `oficinas` e `inscricoes`, agrupando por oficina e calculando a média de `frequencia_percentual` (use `AVG(...)`).
2. Ordene o resultado da maior para a menor média (`ORDER BY ... DESC`).
3. Escreva, em uma frase, qual oficina teve o melhor desempenho médio.

In [36]:
# ✏️ Espaço para resposta/código — Aprofundamento
consulta_aprofundamento = None  # substitua por sua consulta SQL com AVG, GROUP BY e ORDER BY ... DESC

resultado_aprofundamento = None  # substitua por pd.read_sql_query(consulta_aprofundamento, conexao)
conclusao_aprofundamento = "Escreva aqui, em uma frase, qual oficina teve a melhor média e por quê você chegou a essa conclusão..."

resultado_aprofundamento

<details>
<summary>🔓 <b>Clique aqui para ver a solução do professor — Aprofundamento</b></summary>

```python
consulta_aprofundamento = '''
SELECT
    o.nome_oficina,
    AVG(i.frequencia_percentual) AS frequencia_media
FROM oficinas AS o
JOIN inscricoes AS i ON o.codigo_oficina = i.codigo_oficina
GROUP BY o.nome_oficina
ORDER BY frequencia_media DESC
'''

resultado_aprofundamento = pd.read_sql_query(consulta_aprofundamento, conexao)

conclusao_aprofundamento = (
    "A oficina 'Python para Iniciantes' teve a maior frequência média entre os participantes inscritos, "
    "considerando os dados fictícios utilizados nesta atividade."
)
```

**Explicação:** `AVG()` calcula a média por grupo (`GROUP BY o.nome_oficina`), e `ORDER BY frequencia_media DESC` coloca a maior média primeiro.
</details>

In [37]:
# ✅ Verificação automática — Aprofundamento
_pendente = resultado_aprofundamento is None or "Escreva aqui" in str(conclusao_aprofundamento)
if not _pendente:
    _esperado = pd.read_sql_query('''
        SELECT o.nome_oficina, AVG(i.frequencia_percentual) AS frequencia_media
        FROM oficinas AS o
        JOIN inscricoes AS i ON o.codigo_oficina = i.codigo_oficina
        GROUP BY o.nome_oficina
        ORDER BY frequencia_media DESC
    ''', conexao)
    _ok = (list(resultado_aprofundamento["nome_oficina"]) == list(_esperado["nome_oficina"])
           and len(str(conclusao_aprofundamento)) > 20)
    verificar(_ok, "Confira o GROUP BY (por nome_oficina), o uso de AVG() e a ordenação decrescente (DESC).")
else:
    verificar(False, "", ainda_nao_resolvido=True)

📝 Ainda não resolvido — complete o código acima antes de verificar.

---
## 🎫 Ticket de saída

Antes de encerrar a aula, responda rapidamente (pode ser em voz alta, no caderno ou aqui mesmo no notebook):

1. Em uma frase, o que é uma **entidade** em um modelo conceitual?
2. Qual a diferença entre `INNER JOIN` e `LEFT JOIN`? Dê um exemplo.
3. O que significa "junção múltipla"?
4. De 0 a 5, o quanto você se sente confiante para escrever uma consulta com `LEFT JOIN` combinando três tabelas? (0 = nada confiante, 5 = totalmente confiante)

In [38]:
# ✏️ Espaço para resposta/código — Ticket de saída
ticket_pergunta_1_entidade = "Escreva sua resposta aqui..."
ticket_pergunta_2_inner_left = "Escreva sua resposta aqui..."
ticket_pergunta_3_juncao_multipla = "Escreva sua resposta aqui..."
ticket_confianca_0_a_5 = None  # escreva um número de 0 a 5

print("Ticket de saída registrado. Obrigado(a) pela participação!")

Ticket de saída registrado. Obrigado(a) pela participação!

---
## 📊 Rubrica formativa simples

Use esta rubrica para autoavaliação ou para o professor registrar o encaminhamento de cada estudante.

| Critério | Iniciante | Em desenvolvimento | Consolidado |
|---|---|---|---|
| **Modelo conceitual (entidades, atributos, relacionamentos)** | Não identifica entidades nem atributos no cenário proposto. | Identifica entidades e atributos, mas confunde chave primária/estrangeira. | Identifica entidades, atributos, chave primária e relacionamentos com autonomia. |
| **Cardinalidade e participação** | Não distingue 1:1, 1:N e N:N. | Distingue as cardinalidades, mas erra a classificação de participação (opcional/obrigatória). | Classifica corretamente cardinalidade e participação em novos cenários. |
| **Junções externas (LEFT JOIN)** | Não diferencia `INNER JOIN` de `LEFT JOIN`. | Escreve um `LEFT JOIN` simples, mas tem dificuldade para interpretar os valores nulos. | Escreve e interpreta corretamente um `LEFT JOIN`, identificando registros sem correspondência. |
| **Junções múltiplas** | Não consegue combinar mais de duas tabelas. | Combina três tabelas com apoio/exemplo-modelo. | Combina três ou mais tabelas com autonomia, usando aliases, seleção de colunas e ordenação. |

**Encaminhamento sugerido:**
- **Consolidado** em todos os critérios → avançar para o próximo conteúdo do escopo-sequência, com desafios de aprofundamento.
- **Em desenvolvimento** em um ou dois critérios → nova prática guiada, com exemplo-modelo antes da atividade individual.
- **Iniciante** em algum critério → nova intervenção individual, com o cartão sem código e consultas parcialmente preenchidas.

---
## 📓 Texto pronto para registro no diário de classe

### EEBFM — 3ª Série A Técnico — Banco de Dados e Computação em Nuvem — 29/07/2026

> Aula 1 (19h35) e Aula 2 (20h25) — RECUPERAÇÃO E APROFUNDAMENTO: retomada das defasagens da 1ª Ficha de Diagnóstico em Banco de Dados e Computação em Nuvem. Aula 1: modelo conceitual — entidades, atributos, chave primária, relacionamentos, cardinalidade (1:1, 1:N, N:N) e participação (opcional/obrigatória), com atividades de leitura e construção de modelo ER. Aula 2 (formato integrado): junções externas (`LEFT JOIN`) e junções múltiplas (três ou mais tabelas), com construção de banco de dados escolar simulado em SQLite, execução de consultas SQL com pandas, exercícios graduados com verificação automática, desafio final integrador de modelagem e consulta, ticket de saída e rubrica formativa. Todos os dados utilizados são fictícios.

### EEJC — 3ª BT — Banco de Dados e Computação em Nuvem — 30 e 31/07/2026

> **30/07 (08h40–09h30):** RECUPERAÇÃO E APROFUNDAMENTO — modelo conceitual: entidades, atributos, chave primária, relacionamentos, cardinalidade (1:1, 1:N, N:N) e participação (opcional/obrigatória), com atividades de leitura e construção de modelo ER e diagnóstico inicial.
>
> **31/07 (07h00–07h50):** RECUPERAÇÃO E APROFUNDAMENTO — junções externas: `INNER JOIN` x `LEFT JOIN`, registros sem correspondência, comparação visual dos resultados, com banco de dados escolar simulado em SQLite e exercícios graduados com verificação automática.
>
> **31/07 (07h50–08h40):** RECUPERAÇÃO E APROFUNDAMENTO — junções múltiplas: consultas com três ou mais tabelas, aliases, seleção de colunas e ordenação; desafio final integrador de modelagem e consulta; ticket de saída e rubrica formativa. Todos os dados utilizados são fictícios.

---

### 🔐 Proteção de dados e LGPD

- Todos os dados utilizados neste notebook são **fictícios**, criados diretamente no código (identificadores como `EST001`, `P01`, apelidos genéricos como "Estudante Alfa").
- Nenhum nome real, RA, data de nascimento ou diagnóstico de estudante — inclusive da Educação Especial — foi utilizado neste material.
- Este notebook pode ser compartilhado livremente com estudantes e famílias, pois não contém qualquer dado pessoal.

---

**Professor:** Heglas Oliveira — SEDUC-SP — EEBFM / EEJC
**E-mails institucionais:** heglasoliveira@professor.educacao.sp.gov.br | heglasoliveira@prof.educacao.sp.gov.br